//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.Session = new HashSet<Session>();
            this.Genre = new HashSet<Genre>();
        }
    
        public int Film_ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Year_of_issue { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> AgeCategory_ID { get; set; }
        public Nullable<int> FilmCompany_ID { get; set; }
        public Nullable<int> Country_ID { get; set; }
    
        public virtual AgeCategory_ID AgeCategory_ID1 { get; set; }
        public virtual FilmCompany FilmCompany { get; set; }
        public virtual Сountry Сountry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Session> Session { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Genre> Genre { get; set; }
    }
}
