//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Ticket_ID { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> Place_ID { get; set; }
        public Nullable<bool> SoldOut { get; set; }
    
        public virtual Place Place { get; set; }
        public virtual Session Session { get; set; }
    }
}
